In [ ]:
import numpy as np 
import pandas as pd

In [5]:
df = pd.read_csv("ipl.csv")
df.index = df.index + 1
df.head(5)

,team1,team2,match_date,toss_winner,toss_decision,winner,player_of_match,venue,city,team1_players,team2_players,season,match_number,match_type,result,result_margin,target_runs,target_overs,super_over
1,Royal Challengers Bangalore,Kolkata Knight Riders,2008-04-18,Royal Challengers Bangalore,field,Kolkata Knight Riders,BB McCullum,M Chinnaswamy Stadium,Bangalore,"R Dravid, W Jaffer, V Kohli, JH Kallis, CL Whi...","SC Ganguly, BB McCullum, RT Ponting, DJ Hussey...",1,1,League,runs,140.0,223.0,20.0,N
2,Kings XI Punjab,Chennai Super Kings,2008-04-19,Chennai Super Kings,bat,Chennai Super Kings,MEK Hussey,"Punjab Cricket Association Stadium, Mohali",Chandigarh,"K Goel, JR Hopes, KC Sangakkara, Yuvraj Singh,...","PA Patel, ML Hayden, MEK Hussey, MS Dhoni, SK ...",1,2,League,runs,33.0,241.0,20.0,N
3,Delhi Daredevils,Rajasthan Royals,2008-04-19,Rajasthan Royals,bat,Delhi Daredevils,MF Maharoof,Feroz Shah Kotla,Delhi,"G Gambhir, V Sehwag, S Dhawan, MK Tiwary, KD K...","T Kohli, YK Pathan, SR Watson, M Kaif, DS Lehm...",1,3,League,wickets,9.0,130.0,20.0,N
4,Mumbai Indians,Royal Challengers Bangalore,2008-04-20,Mumbai Indians,bat,Royal Challengers Bangalore,MV Boucher,Wankhede Stadium,Mumbai,"L Ronchi, ST Jayasuriya, DJ Thornely, RV Uthap...","S Chanderpaul, R Dravid, LRPL Taylor, JH Kalli...",1,4,League,wickets,5.0,166.0,20.0,N
5,Kolkata Knight Riders,Deccan Chargers,2008-04-20,Deccan Chargers,bat,Kolkata Knight Riders,DJ Hussey,Eden Gardens,Kolkata,"WP Saha, BB McCullum, RT Ponting, SC Ganguly, ...","AC Gilchrist, Y Venugopal Rao, VVS Laxman, A S...",1,5,League,wickets,5.0,111.0,20.0,N

In [8]:
new_df = df[(df["team1"] == "Royal Challengers Bangalore") | (df["team2"] == "Royal Challengers Bangalore" )].copy()
new_df

,team1,team2,match_date,toss_winner,toss_decision,winner,player_of_match,venue,city,team1_players,team2_players,season,match_number,match_type,result,result_margin,target_runs,target_overs,super_over
1,Royal Challengers Bangalore,Kolkata Knight Riders,2008-04-18,Royal Challengers Bangalore,field,Kolkata Knight Riders,BB McCullum,M Chinnaswamy Stadium,Bangalore,"R Dravid, W Jaffer, V Kohli, JH Kallis, CL Whi...","SC Ganguly, BB McCullum, RT Ponting, DJ Hussey...",1,1,League,runs,140.0,223.0,20.0,N
4,Mumbai Indians,Royal Challengers Bangalore,2008-04-20,Mumbai Indians,bat,Royal Challengers Bangalore,MV Boucher,Wankhede Stadium,Mumbai,"L Ronchi, ST Jayasuriya, DJ Thornely, RV Uthap...","S Chanderpaul, R Dravid, LRPL Taylor, JH Kalli...",1,4,League,wickets,5.0,166.0,20.0,N
12,Royal Challengers Bangalore,Rajasthan Royals,2008-04-26,Rajasthan Royals,field,Rajasthan Royals,SR Watson,M Chinnaswamy Stadium,Bangalore,"S Chanderpaul, R Dravid, LRPL Taylor, JH Kalli...","GC Smith, M Rawat, YK Pathan, SR Watson, M Kai...",1,12,League,wickets,9.0,148.0,20.0,N
15,Royal Challengers Bangalore,Chennai Super Kings,2008-04-28,Chennai Super Kings,bat,Chennai Super Kings,MS Dhoni,M Chinnaswamy Stadium,Bangalore,"B Chipli, W Jaffer, LRPL Taylor, JH Kallis, MV...","PA Patel, ML Hayden, MEK Hussey, SK Raina, MS ...",1,15,League,runs,13.0,179.0,20.0,N
17,Delhi Daredevils,Royal Challengers Bangalore,2008-04-30,Royal Challengers Bangalore,field,Delhi Daredevils,GD McGrath,Feroz Shah Kotla,Delhi,"G Gambhir, V Sehwag, S Dhawan, Shoaib Malik, K...","P Kumar, W Jaffer, LRPL Taylor, JH Kallis, R D...",1,17,League,runs,10.0,192.0,20.0,N
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
999,Royal Challengers Bangalore,Delhi Capitals,2023-05-06,Royal Challengers Bangalore,bat,Delhi Capitals,PD Salt,"Arun Jaitley Stadium, Delhi",Delhi,"HV Patel, V Kohli, F du Plessis, GJ Maxwell, M...","I Sharma, DA Warner, PD Salt, MR Marsh, RR Ros...",16,49,League,wickets,6.0,140.0,20.0,N
1004,Royal Challengers Bangalore,Mumbai Indians,2023-05-09,Mumbai Indians,field,Mumbai Indians,SA Yadav,"Wankhede Stadium, Mumbai",Mumbai,"V Kohli, F du Plessis, Anuj Rawat, GJ Maxwell,...","Ishan Kishan, RG Sharma, SA Yadav, N Wadhera, ...",16,54,League,wickets,6.0,200.0,20.0,N
1011,Royal Challengers Bangalore,Rajasthan Royals,2023-05-14,Royal Challengers Bangalore,bat,Royal Challengers Bangalore,WD Parnell,"Sawai Mansingh Stadium, Jaipur",Jaipur,"Shahbaz Ahmed, V Kohli, F du Plessis, GJ Maxwe...","YS Chahal, YBK Jaiswal, JC Buttler, SV Samson,...",16,61,League,wickets,6.0,145.0,20.0,N
1015,Sunrisers Hyderabad,Royal Challengers Bangalore,2023-05-18,Royal Challengers Bangalore,field,Royal Challengers Bangalore,V Kohli,"Rajiv Gandhi International Stadium, Uppal, Hyd...",Hyderabad,"T Natarajan, Abhishek Sharma, RA Tripathi, AK ...","V Kohli, F du Plessis, GJ Maxwell, MG Bracewel...",16,65,League,wickets,8.0,187.0,20.0,N
1019,Royal Challengers Bangalore,Gujarat Titans,2023-05-21,Gujarat Titans,field,Gujarat Titans,Shubman Gill,"M Chinnaswamy Stadium, Bengaluru",Bengaluru,"H Sharma, V Kohli, F du Plessis, GJ Maxwell, M...","Yash Dayal, WP Saha, Shubman Gill, V Shankar, ...",16,69,League,wickets,8.0,201.0,20.0,N

In [14]:
new_df = new_df.drop(columns=["match_date","player_of_match","city","team1_players","team2_players","match_number","result","result_margin","target_runs","target_overs","super_over"])

In [15]:
new_df["result"] = new_df["winner"].apply(lambda x: "won" if x =="Royal Challengers Bangalore" else "lost")
new_df

,team1,team2,toss_winner,toss_decision,winner,venue,season,match_type,result
1,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,field,Kolkata Knight Riders,M Chinnaswamy Stadium,1,League,lost
4,Mumbai Indians,Royal Challengers Bangalore,Mumbai Indians,bat,Royal Challengers Bangalore,Wankhede Stadium,1,League,won
12,Royal Challengers Bangalore,Rajasthan Royals,Rajasthan Royals,field,Rajasthan Royals,M Chinnaswamy Stadium,1,League,lost
15,Royal Challengers Bangalore,Chennai Super Kings,Chennai Super Kings,bat,Chennai Super Kings,M Chinnaswamy Stadium,1,League,lost
17,Delhi Daredevils,Royal Challengers Bangalore,Royal Challengers Bangalore,field,Delhi Daredevils,Feroz Shah Kotla,1,League,lost
...,...,...,...,...,...,...,...,...,...
999,Royal Challengers Bangalore,Delhi Capitals,Royal Challengers Bangalore,bat,Delhi Capitals,"Arun Jaitley Stadium, Delhi",16,League,lost
1004,Royal Challengers Bangalore,Mumbai Indians,Mumbai Indians,field,Mumbai Indians,"Wankhede Stadium, Mumbai",16,League,lost
1011,Royal Challengers Bangalore,Rajasthan Royals,Royal Challengers Bangalore,bat,Royal Challengers Bangalore,"Sawai Mansingh Stadium, Jaipur",16,League,won
1015,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,Royal Challengers Bangalore,"Rajiv Gandhi International Stadium, Uppal, Hyd...",16,League,won
1019,Royal Challengers Bangalore,Gujarat Titans,Gujarat Titans,field,Gujarat Titans,"M Chinnaswamy Stadium, Bengaluru",16,League,lost

In [ ]:
new_df2 = df["venue"].value_counts()
new_df2